config/routes.rb
Hacklife::Application.routes.draw do
  devise_for :users
  root 'life_hacks#index'
  get 'about' => 'life_hacks#about'

  resources :life_hacks, only: [:new, :index, :create, :show, :destroy] do
    resources :reviews, only: [:new, :create]
  end

  resources :reviews, only: [:show, :destroy] do
    resources :comments, only: [:new, :create, :destroy]
  end

  resources :likes, only: [:create, :update]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :body, presence: true
  validates :review, presence: true
  validates :user, presence: true
  belongs_to :user
  belongs_to :review
end

app/models/life_hack.rb
class LifeHack < ActiveRecord::Base
  validates :title, presence: true
  validates :content, presence: true
  belongs_to :user
  has_many :reviews, dependent: :destroy

  def self.search(search)
    if search
      where("title ilike ? or content ilike ?", "%#{search}%","%#{search}%")
    else
      find(:all)
    end
  end


  def rating
    rating = 0
    count = 0
    if reviews.exists?
      reviews.each do |review|
        rating += review.rating
        count += 1
      end
    end
    if count != 0
      rating/count
    else
        0
    end
  end

end

app/models/like.rb
class Like < ActiveRecord::Base
  validates_uniqueness_of :user_id, scope: :review_id
  validates_inclusion_of :score, :in => [-1,1]
  belongs_to :review
  belongs_to :user
end

app/models/review.rb
class Review < ActiveRecord::Base
  validates :title, presence: true
  validates :body, presence: true
  validates :rating, presence: true, numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: 6 }

  has_many :comments, dependent: :destroy
  has_many :likes
  belongs_to :user
  belongs_to :life_hack

  def self.score_count(review)
    total_score = 0
    review.likes.each do |like|
      total_score += like.score
    end
    total_score
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true
  validates :username, presence: true, uniqueness: true
  has_many :life_hacks
  has_many :reviews
  validates :admin, inclusion: { in: [true, false] }
  has_many :likes

  mount_uploader :avatar, AvatarUploader

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
    admin == true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:name, :username, :avatar]
  end

  def authorize_user
    unless user_signed_in? && current_user.admin?
      raise ActionController::RoutingError.new('Not Found')
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create, :destroy]
  before_filter :authorize_user, only: :destroy

  def new
    @review = Review.find(params[:review_id])
    @comment = Comment.new
  end

  def create
    params[:comment][:user_id] = current_user.id
    @review = Review.find(params[:review_id])
    @comment = @review.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to review_path(@review),
      notice: 'Comment was successfully added'
    else
      flash[:alert] = 'Comment unsuccessful'
      render :new
    end
  end

  def destroy
    @review = Review.find(params[:review_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to root_path, notice: "Comment Deleted"
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :review_id)
  end

end

app/controllers/life_hacks_controller.rb
class LifeHacksController < ApplicationController
  before_filter :authenticate_user!, only: [:create, :new, :destroy]
  before_filter :authorize_user, only: :destroy

  def new
    @life_hack = LifeHack.new
  end

  def create
    @life_hack = LifeHack.new(life_hack_params)
    @life_hack.user = current_user
    if @life_hack.save
      redirect_to '/life_hacks', notice: 'LifeHack was successfully added'
    else
      render :new
    end
  end

  def index
    if params[:search]
      @life_hacks = LifeHack.search(params[:search]).page(params[:page]).per(20)
    else
      @life_hacks = LifeHack.all.page(params[:page]).per(20)
    end
  end

  def about

  end

  def show
    @life_hack = LifeHack.find(params[:id])
  end

  def destroy
    @life_hack = LifeHack.find(params[:id])
    @life_hack.destroy
    redirect_to root_path, notice: "Article Deleted"
  end

  private

  def life_hack_params
    params.require(:life_hack).permit(:title, :link, :content)
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_filter :authenticate_user!

   def create
    @like = Like.new(like_params)
    @like.user = current_user
    if @like.save
      redirect_to review_path(@like.review),
      notice: 'You Voted!'
    else
      redirect_to review_path(@like.review),
      alert: 'Vote failed.'
    end
   end

   def update
    @like = current_user.likes.find(params[:id])
    @like.update(like_params)
    flash[:notice] = 'Updated.'
    redirect_to review_path(@like.review)
  end


  private

  def like_params
    params.require(:like).permit(:score, :review_id)
  end



end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :authenticate_user!, only: [:create, :new, :destroy]
  before_filter :authorize_user, only: :destroy

  def new
    @life_hack = LifeHack.find(params[:life_hack_id])
    @review = Review.new
  end

  def create
    @life_hack = LifeHack.find(params[:life_hack_id])
    @review = @life_hack.reviews.build(review_params)
    @review.user = current_user

    if @review.save
      ReviewMailer.notify(@life_hack.user).deliver
      redirect_to life_hack_path(@life_hack),
        notice: 'Review was successfully added'
    else
      flash[:notice] = "Fields can't be blank"
      render :new
    end
  end

  def show
    @review = Review.find(params[:id])
    @like = @review.likes.find_by(user: current_user) || Like.new
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to root_path, notice: "Review Deleted"
  end

  private

  def review_params
    params.require(:review).permit(:title,:body,:rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<h1>Add a Comment</h1>

<%= simple_form_for [@review, @comment] do |f| %>
  <%= f.input :body %>
  <%= f.button :submit, 'Submit Comment' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <div class = 'row'>
      <div class = 'small-12 columns'>

          <nav class = "top-bar">
            <section class='top-bar-section'>

            <div class='medium-8 columns'>
              <ul>
                <li class='name'><%= link_to "Home", root_path %></li>
                <li class='name'><%= link_to "Trending", root_path %></li>
                <% if request.env['PATH_INFO'] != new_user_registration_path && request.env['PATH_INFO'] != '/users' %>

                  <% if !user_signed_in? %>
                    <li class='name'><%= link_to "Sign Up", new_user_registration_path %></li>
                    <li class='name'><%= link_to "Sign In", new_user_session_path %></li>
                  <% else %>
                    <li class='name'><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
                    <li class='name'><%= image_tag(current_user.avatar.url) %></li>
                  <% end %>

                <% end %>

                <li class='name'><%= link_to "About", about_path %></li>
                <li class='name'><a href="#" class="fc-webicon facebook">Like us on Facebook</a></li>

              </ul>

            </div>
            <di class='small-3 columns'>
              <ul class = 'right'>
                <%= form_tag(life_hacks_path(), method: :get) do %>
                    <%= text_field_tag :search, params[:search] %>
                    <%= submit_tag "Search Life Hacks" %>
                <% end %>
              </ul>
            </div>
          </nav>


        <% if flash[:notice].present? %>
          <%= flash[:notice] %>
        <% end %>

        <% if flash[:alert].present? %>
          <%= flash[:alert] %>
        <% end %>

        <% if user_signed_in? %>
          <h2>Welcome <%= current_user.name %></h2>
        <% end %>

        <%= yield %>

      </div>
    </div>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/life_hacks/about.html.erb
<div class='row'>
  <div class='small-6 columns'>
    Daniel Rubio
  </div>
  <div class='small-6 columns'>
</div>

<div class='row'>
  <h2>Team Lead: Adam's Beard</h2>
</div>

app/views/life_hacks/index.html.erb
<h1>LifeHacks</h1>
<p><%= link_to 'Add Life Hack', new_life_hack_path %></p>

<%= paginate @life_hacks %>

    <% @life_hacks.each do |life_hack| %>
    <div class='lifehack'>
      <%= life_hack.rating %>Stars
      <%= link_to life_hack.title, life_hack %>
      <%= life_hack.content %>
    </div>
    <% end %>

app/views/life_hacks/new.html.erb
<%= simple_form_for(@life_hack) do |f| %>
  <%= f.input :title %>
  <%= f.input :link %>
  <%= f.input :content %>
  <%= f.button :submit, 'Submit Hack' %>
<% end %>

app/views/life_hacks/show.html.erb
<h1><%= @life_hack.title %></h1>
<p><%= @life_hack.content %></p>

<%= link_to "Add a Review", new_life_hack_review_path(@life_hack)%>
<% if @life_hack.reviews.present? %>
  <div>
    <ul>
      <%  @life_hack.reviews.each do |review| %>
        <li>
          <h4><%= link_to review.title, review_path(review) %></h4>
          <%= review.body %>
        </li>
      <%end%>
    </ul>
  </div>
<% end %>

<ul>
<% if user_signed_in? && current_user.admin? %>
  <li><%= link_to 'Delete', life_hack_path(@life_hack), method: :delete %><li>
<% end %>
</ul>

<%= link_to "Back to Life Hacks", life_hacks_path %>

app/views/reviews/new.html.erb
<h1> Add a Review For This Article </h1>

<%= simple_form_for [@life_hack, @review] do |f| %>
  <%= f.input :title %>
  <%= f.input :body %>
  <%= f.input :rating, collection: 1..5, as: :radio_buttons,
          item_wrapper_class: 'inline' %>
  <%= f.button :submit, 'Submit Review' %>
<% end %>

app/views/reviews/show.html.erb
<h1><%= params[:title] %></h1>

<div><%= params[:body] %></div>

  <%= simple_form_for @like do |f| %>
  <%= f.hidden_field :review_id, value: @review.id %>
  <%= f.hidden_field :score, value: 1 %>
  <%= f.button :submit,'Like' %>
  <% end %>

  <%= simple_form_for @like do |f| %>
  <%= f.hidden_field :review_id, value: @review.id %>
  <%= f.hidden_field :score, value: -1 %>
  <%= f.button :submit,'Dislike' %>
  <% end %>

  <div>
    <h3> Likes </h3>
    <%=Review.score_count(@review) %>
  </div>

<h3>Comments</h3>

<%= link_to 'Add a Comment', new_review_comment_path(@review) %>

<% if @review.comments.present? %>
  <div>
    <ul>
      <%  @review.comments.each do |comment| %>
        <li>
          <%= comment.body %>
          <% if user_signed_in? && current_user.admin? %>
            <%= link_to 'Delete Comment', review_comment_path(@review, comment), method: :delete %>
          <% end %>
        </li>
      <%end%>
    </ul>
  </div>
<% end %>

<ul>
<% if user_signed_in? && current_user.admin? %>
  <li><%= link_to 'Delete', review_path(@review), method: :delete %></li>
  <% end %>
</ul>

<%= link_to 'Back to Hack', life_hacks_path %>